//All Products Action Types
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

//Login Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//Registeration Action Types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//Categories Action Types
export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";

// Hamburger Menu Action Type
export const TOGGLE_HAMBURGER = "TOGGLE_HAMBURGER";

// Products by Categories Action Types
export const GET_PRODUCTS_BY_CATEGORIES_REQUEST =
  "GET_PRODUCTS_BY_CATEGORIES_REQUEST";
export const GET_PRODUCTS_BY_CATEGORIES_SUCCESS =
  "GET_PRODUCTS_BY_CATEGORIES_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORIES_FAILURE =
  "GET_PRODUCTS_BY_CATEGORIES_FAILURE";

// ADD Product to Cart Action Types
export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILURE = "ADD_PRODUCT_TO_CART_FAILURE";

// Get Cart Action Types
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

// REmove cart Item Action Types
export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";

// Increase Quantity of Cart Item Action Types
export const INCREASE_CART_ITEM_QUANTITY_REQUEST =
  "INCREASE_CART_ITEM_QUANTITY_REQUEST";
export const INCREASE_CART_ITEM_QUANTITY_SUCCESS =
  "INCREASE_CART_ITEM_QUANTITY_SUCCESS";
export const INCREASE_CART_ITEM_QUANTITY_FAILURE =
  "INCREASE_CART_ITEM_QUANTITY_FAILURE";

//Decrease Quantity of Cart Item Action Types
export const DECREASE_CART_ITEM_QUANTITY_REQUEST =
  "DECREASE_CART_ITEM_QUANTITY_REQUEST";
export const DECREASE_CART_ITEM_QUANTITY_SUCCESS =
  "DECREASE_CART_ITEM_QUANTITY_SUCCESS";
export const DECREASE_CART_ITEM_QUANTITY_FAILURE =
  "DECREASE_CART_ITEM_QUANTITY_FAILURE";

// Get the single Product Action Types
export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAILURE = "SINGLE_PRODUCT_FAILURE";

// Post an Order Action Types
export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";

// Get User's Orders
export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILURE = "GET_USER_ORDERS_FAILURE";

// Add to wishlist Action Types
export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";

//Get Wishlist Items Action Types
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";
export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";

// Remove Item from Wishlist Action Types
export const REMOVE_ITEM_FROM_WISHLIST_REQUEST =
  "REMOVE_ITEM_FROM_WISHLIST_REQUEST";
export const REMOVE_ITEM_FROM_WISHLIST_Success =
  "REMOVE_ITEM_FROM_WISHLIST_SUCCESS";
export const REMOVE_ITEM_FROM_WISHLIST_FAILURE =
  "REMOVE_ITEM_FROM_WISHLIST_FAILURE";

// Cancel Order Action Types
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";
