export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

// Update product details Action Types
export const UPDATE_PRODUCT_DETAILS_REQUEST = "UPDATE_PRODUCT_DETAILS_REQUEST";
export const UPDATE_PRODUCT_DETAILS_SUCCESS = "UPDATE_PRODUCT_DETAILS_SUCCESS";
export const UPDATE_PRODUCT_DETAILS_FAILURE = "UPDATE_PRODUCT_DETAILS_FAILURE";

// Delete Product Action Types
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
