export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAILURE = "GET_ALL_OREDR_FAILURE";

//Specific Order Details
export const GET_SPECIFIC_ORDER_DETAILS_REQUEST =
  "GET_SPECIFIC_ORDER_DETAILS_REQUEST";
export const GET_SPECIFIC_ORDER_DETAILS_SUCCESS =
  "GET_SPECIFIC_ORDER_DETAILS_SUCCESS";
export const GET_SPECIFIC_ORDER_DETAILS_FAILURE =
  "GET_SPECIFIC_ORDER_DETAILS_FAILURE";

// Update Order Status Action Types
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";
